name: Release

on:
  push:
    branches:
      - main
      - staging

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - name: deploy
        run: npm run release
